### ISSUE TITLE
Reoccurring PluginException: IntelliJ 2022.3.1

### ISSUE THREAD

**Issue by bobaikato** [chylex/IntelliJ-Colored-Icons#1]
```
Calling `ClassLoader#getResource` with leading slash doesn't work; strip

com.intellij.diagnostic.PluginException: /icons/toolwindows/toolWindowCommit.svg [Plugin: com.chylex.intellij.coloredicons]
	at com.intellij.ide.plugins.cl.PluginClassLoader.doFindResource(PluginClassLoader.java:548)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:456)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1403)
	at com.intellij.ui.RasterizedImageDataLoader.getURL(RasterizedImageDataLoader.kt:67)
	at com.intellij.openapi.util.IconLoader.loadCustomVersion(IconLoader.java:86)
	at com.intellij.openapi.util.IconLoader.loadCustomVersionOrScale(IconLoader.java:114)
	at com.intellij.openapi.wm.impl.SquareStripeButtonKt.scaleIcon(SquareStripeButton.kt:119)
	at com.intellij.openapi.wm.impl.SquareStripeButtonKt.createPresentation(SquareStripeButton.kt:112)
	at com.intellij.openapi.wm.impl.SquareStripeButtonKt.access$createPresentation(SquareStripeButton.kt:1)
	at com.intellij.openapi.wm.impl.SquareStripeButton.<init>(SquareStripeButton.kt:29)
	at com.intellij.toolWindow.ToolWindowPaneNewButtonManager.createStripeButton(ToolWindowPaneNewButtonManager.kt:131)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.toolWindowAvailable$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1903)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setAvailable(ToolWindowImpl.kt:373)
	at com.intellij.openapi.vcs.changes.ui.VcsToolWindowFactory.updateState(VcsToolWindowFactory.kt:82)
	at com.intellij.openapi.vcs.changes.ui.VcsToolWindowFactory.init$lambda$3$lambda$2(VcsToolWindowFactory.kt:43)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion.scheduleWithinConstraints$inner(BaseConstrainedExecution.kt:67)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution$Companion.scheduleWithinConstraints(BaseConstrainedExecution.kt:70)
	at com.intellij.openapi.application.constraints.BaseConstrainedExecution.scheduleWithinConstraints(BaseConstrainedExecution.kt:37)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl.access$scheduleWithinConstraints$s628187586(BaseExpirableExecutorMixinImpl.kt:12)
	at com.intellij.openapi.application.impl.BaseExpirableExecutorMixinImpl$scheduleWithinConstraints$$inlined$Runnable$1.run(Runnable.kt:19)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by chylex** [comment]
I don't see any exceptions on my end, do you have any other downloaded plugins installed and do the exceptions keep happening if you disable them?

**Comment by bobaikato** [comment]
When you say any other plugins, what do you mean? I certainly use other plugins as well as yours.
I can't tell what's causing the issue. 

Regardless, the exception message seems to tell the source of the issue.

**Comment by bobaikato** [comment]
I just got another exception, this time on ` /icons/toolwindows/notifications.svg`

```
Calling `ClassLoader#getResource` with leading slash doesn't work; strip

com.intellij.diagnostic.PluginException: /icons/toolwindows/notifications.svg [Plugin: com.chylex.intellij.coloredicons]
	at com.intellij.ide.plugins.cl.PluginClassLoader.doFindResource(PluginClassLoader.java:548)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:456)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1403)
	at com.intellij.ui.RasterizedImageDataLoader.getURL(RasterizedImageDataLoader.kt:67)
	at com.intellij.openapi.util.IconLoader.loadCustomVersion(IconLoader.java:86)
	at com.intellij.util.IconUtil.scaleOrLoadCustomVersion(IconUtil.java:682)
	at com.intellij.openapi.wm.impl.ToolWindowIcon.scale(ToolWindowIcon.kt:38)
	at com.intellij.openapi.wm.impl.ToolWindowIcon.scale(ToolWindowIcon.kt:17)
	at com.intellij.ide.actions.ActivateToolWindowAction.updatePresentation(ActivateToolWindowAction.java:106)
	at com.intellij.ide.actions.ActivateToolWindowAction.ensureToolWindowActionRegistered(ActivateToolWindowAction.java:48)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1095)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows$registerToolWindows(ToolWindowSetInitializer.kt:134)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:160)
	at com.intellij.toolWindow.ToolWindowSetInitializer.access$createAndLayoutToolWindows(ToolWindowSetInitializer.kt:46)
	at com.intellij.toolWindow.ToolWindowSetInitializer$initUi$3.invokeSuspend(ToolWindowSetInitializer.kt:106)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by bobaikato** [comment]
I see the pattern, pretty much on every icon I click I get an exception
` /icons/toolwindows/toolWindowTodo.svg`

The error is self-explanatory to be honest.


```
Calling `ClassLoader#getResource` with leading slash doesn't work; strip

com.intellij.diagnostic.PluginException: /icons/toolwindows/toolWindowTodo.svg [Plugin: com.chylex.intellij.coloredicons]
	at com.intellij.ide.plugins.cl.PluginClassLoader.doFindResource(PluginClassLoader.java:548)
	at com.intellij.ide.plugins.cl.PluginClassLoader.findResource(PluginClassLoader.java:456)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1403)
	at com.intellij.ui.RasterizedImageDataLoader.getURL(RasterizedImageDataLoader.kt:67)
	at com.intellij.openapi.util.IconLoader.loadCustomVersion(IconLoader.java:86)
	at com.intellij.openapi.util.IconLoader.loadCustomVersionOrScale(IconLoader.java:114)
	at com.intellij.openapi.wm.impl.SquareStripeButtonKt.scaleIcon(SquareStripeButton.kt:119)
	at com.intellij.openapi.wm.impl.SquareStripeButtonKt.access$scaleIcon(SquareStripeButton.kt:1)
	at com.intellij.openapi.wm.impl.SquareAnActionButton.isSelected(SquareStripeButton.kt:145)
	at com.intellij.ui.ToggleActionButton.updateButton(ToggleActionButton.java:50)
	at com.intellij.ui.AnActionButton.update(AnActionButton.java:112)
	at com.intellij.openapi.actionSystem.AnAction.beforeActionPerformedUpdate(AnAction.java:324)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performDumbAwareUpdate$0(ActionUtil.java:150)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:176)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lastUpdateAndCheckDumb(ActionUtil.java:272)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:175)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:465)
	at java.desktop/java.awt.Component.processEvent(Component.java:6413)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:831)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:753)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by bobaikato** [comment]
One final observation. Your plugin works fine with the old UI, not the NEW UI.

Switch to the new UI and see if you can replicate the problem
<img width="931" alt="image" src="https://user-images.githubusercontent.com/14136806/209525880-6dc46d52-e238-4641-b81b-6422d8cf6162.png">

**Comment by chylex** [comment]
I don't use nor support the new UI. The settings page says the new UI is a work in progress, so I might support it once it's finished.

**Comment by chylex** [comment]
I pushed a fix for the exception, however new UI is not and will not be supported until it is the only UI, so there is no reason to use the plugin with it.

Since it's a low impact issue I won't release an update just for this fix, if I add new icons or something else comes up I will release the update then.

**Comment by bobaikato** [comment]
Hey, @chylex I want to invite you to  https://public.gives/ A social giving app I just released to beta.

It's a platform where you can receive public appreciation for your work on open source and also a place where many other can discover your work.

Beta is on iOS, if you are eager to try it get it here. https://public.gives/beta

**Comment by chylex** [comment]
I deleted the last comment, at first glance it looked like spam from a random account and I didn't check who the commenter was. Either way it was not related to the issue or project so I would have flagged it as off-topic, but I wanted to explain what happened.
